pgRouting/osm2pgrouting

src/Export2DB.cpp, src/Export2DB.h, src/osm2pgrouting.cpp, src/prog_options.cpp
=> Gsoc develop

run.sh, src/Export2DB.cpp, src/Export2DB.h, src/OSMDocument.cpp, src/OSMDocumentParserCallback.cpp, src/Relation.h, src/osm2pgrouting.cpp, src/prog_options.cpp
Missing vertices table to not generate repeated when incremental feature is used.
=> Merge dev gsoc cleanup

src/Class.cpp, src/Configuration.cpp, src/Configuration.h, src/ConfigurationParserCallback.cpp, src/ConfigurationParserCallback.h, src/Node.cpp, src/Node.h, src/OSMDocument.cpp, src/OSMDocument.h, src/Relation.cpp, src/Relation.h, src/Way.cpp, src/Way.h, src/XMLParser.cpp, src/math_functions.cpp, src/math_functions.h, src/prog_options.cpp, src/prog_options.h, src/utils.h, tools/doxygen/Doxyfile
=> Fn documentation

src/Export2DB.cpp, src/Export2DB.h, src/osm2pgrouting.cpp, src/prog_options.cpp
Breaking up in chinks of 100000 edges for insertion in database
and no default prefix.
=> Vdev in chunks

Readme.md, src/Export2DB.cpp, src/Export2DB.h, src/osm2pgrouting.cpp, src/prog_options.cpp
=> With schema

src/Export2DB.cpp, src/osm2pgrouting.cpp, src/prog_options.cpp, src/prog_options.h
=> fixes #121

src/Export2DB.cpp, src/OSMDocument.cpp, src/OSMDocument.h, src/osm2pgrouting.cpp
The spelling error was reported by the lintian QA tool for the Debian package build:
* splitted -> split
=> Fix spelling errors.

Readme.md, src/Export2DB.cpp, src/Node.cpp, src/Node.h, src/OSMDocument.cpp, src/OSMDocumentParserCallback.cpp, src/Relation.cpp, src/Relation.h, src/Way.cpp, src/Way.h
- Works for Nodes
- Doesn't work for other entities, need fix for ways (minimum) to get imported into db
=> Extraction with version & timestamp

src/Export2DB.cpp, src/osm2pgrouting.cpp
Fixed names on  createFKeys() function
=> Ldesousa fkeys

CMakeLists.txt, src/Export2DB.cpp, src/Way.h, src/osm2pgrouting.cpp
adding wrappers so it compiles with g++4.4 (used in centos)
=> wrap Range loos for g++4.4

src/Export2DB.cpp
table osm_way_tags is not generated any more
=> removed ERROR:  relation "osm_way_tags" does not exist

src/OSMDocumentParserCallback.cpp, src/osm2pgrouting.cpp
=> changed the parsing progress line way of working

include/configuration/configuration.h, src/configuration/configuration.cpp, src/configuration/tag_key.cpp, src/database/Export2DB.cpp, src/osm_elements/Way.cpp
fix: the values of  maxspeed forward & backward
=> fixed maxspeed forward & backward

include/osm_elements/OSMDocument.h, src/database/Export2DB.cpp, src/database/table_management.cpp, src/osm_elements/OSMDocument.cpp, src/osm_elements/osm2pgrouting.cpp, src/parser/OSMDocumentParserCallback.cpp, src/utilities/prog_options.cpp
=> Fixing fork flag

NEWS, src/database/Export2DB.cpp, src/osm_elements/OSMDocument.cpp, src/osm_elements/osm2pgrouting.cpp, src/osm_elements/osm_element.cpp, src/parser/OSMDocumentParserCallback.cpp, src/utilities/handle_pgpass.cpp
=> Fix issue189

src/osm_elements/osm2pgrouting.cpp
Hi,
Fixed version (print 2.3.1 -> 2.3.2).
Thanks,
=> fixed version (print 2.3.1 -> 2.3.2)

src/database/Export2DB.cpp, src/database/table_management.cpp
=> added CASCADE to the drop statements

include/database/Export2DB.h, src/database/Export2DB.cpp, src/osm_elements/osm2pgrouting.cpp
Fixes #204 
No need to put the clean flag when the database is new (does not have the tables)
=> automatically checks if a table exists and creates it if not

CMakeLists.txt, Readme.md
Follow up of #203 
FindLibPQXX.cmake does not find the version of libpqxx
=> Issue pr203

Readme.md
Hi all,
I have improved main Readme doc with the following contents:
- Tips section: A lot of issues in this repository are related with large OSM files imports. If we put some little tips in the main Readme doc I think a lot of issues can solve themselves. In the future we can include more tips.
- Table of contents: this is for a better navigation by contents.
Thanks,
Cayetano
=> Readme doc improvements

NEWS, src/osm_elements/osm2pgrouting.cpp
@cvvergara PR with basic things for next release 2.3.5.
=> Preparing next release

how_to_release.md
@cvvergara the pending doc about how to release a new version.
=> how to release doc

src/utilities/prog_options.cpp
=> Command line configuration in print outputs (db password)

NEWS
=> updated news doc

NEWS, src/osm_elements/osm2pgrouting.cpp
Hi,
New release launched with minor version 2.3.6: https://github.com/pgRouting/osm2pgrouting/releases
The goal of this PR is update master branch with next release 2.3.7. I've created new milestone.
Thanks,
=> New minor version and next release

README.md
=> remove postgis flag from README

src/osm_elements/Way.cpp
Fixes #266 .
- Way - fixed bug handling onway false conditions
=> Way - fixed bug handling onway false conditions

mapconfig.xml
Fixes # .
- Add comments for documentation
=> add a comments for better understandig

mapconfig_for_bicycles.xml
Fixes # .
- set priority of highway=track to 2.0 to get the tracktype if present.
- add some documentation
- remove junction roundabout (this should normally never come to evaluation)
=> some documentation

NEWS
- NEWS file updated for v2.3.7
=> NEWS file updated for v2.3.7

docs/how_to_release.md
- fixed docs - master branch to main branch
=> fixed docs - master branch to main branch

NEWS, src/osm_elements/osm2pgrouting.cpp
=> new dev version 2.3.9
